### ISSUE TITLE
Some questions about dataset creating

### ISSUE THREAD

**Issue by cauchy-max** [Imageomics/bioclip#17]
Hi, this paper has brought a great progress for Tree of Life and I want to reproduce the whole experiments. I am not sure about how to correctly the dataset and I follow the "treeoflife10m.md" to create the dataset. I have finished the first step and got  an error at the second step "python scripts/evobio10m/make_mapping.py --tag v3.3 --workers 8". The error is as follows:
ModuleNotFoundError: No module named 'imageomics'
What can I do to solve this problem?

**Comment by thompsonmj** [comment]
Thanks for your interest!

The `imageomics` modules should be made available once you do `pip install .` from the `bioclip` root directory within your virtual environment. 

Further, the dataset recreation process starts at step 6 in the current version of the [`treeoflife10m.md`](https://github.com/Imageomics/bioclip/blob/main/docs/imageomics/treeoflife10m.md) file. However some problems have been identified with this process (#13) which we are in the process of addressing (#14, #16).

**Comment by cauchy-max** [comment]
Thanks for the quick response! Is it correct to apply `pip install imageomics` to acquire imageomics? As I understand, imageomics may be a document that involves disk class and please correct me if I am wrong.
And through your response, Is it right that I just need to "run sbatch slurm/make-dataset-wds.sh on Pitzer" and ignore the second to fifth steps?

**Comment by samuelstevens** [comment]
No, you should `cd` into the `bioclip` directory. When you run `ls`, you should see the `src/` directory, the `README.md` file, etc. Then you should run `pip install -e .` to install the `bioclip` package, which will make `imageomics` available on your path.

**Comment by cauchy-max** [comment]
Thank you very much for telling me the detailed process!!
