### ISSUE TITLE
demo broken?

### ISSUE THREAD

**Issue by boly38** [Imageomics/bioclip#18]
Hi, 

(On my side I'm [studying](https://github.com/boly38/botEnSky/issues/57) some way identify birds)

I would like to test your online demo picking the link from your readme: 
- I put an image and submit the form (keeping "species" selected)

but I've network 405 response in the logs and never ending wait counter 
````
GET https://imageomics-bioclip-demo.hf.space/queue/join?fn_index=3&session_hash=cvs7jh92v2j 405 (Method Not Allowed)
````
![image](https://github.com/Imageomics/bioclip/assets/3100576/c018225e-c1ce-4bd6-ac79-4be7c6b01750)

PS: sorry if it' the wrong place to warn about this.
Regards

**Comment by ysu1989** [comment]
Hi I just tried the demo and it works fine on my end. Is the error reproducible on your end?

**Comment by boly38** [comment]
all right for [demo](https://huggingface.co/spaces/imageomics/bioclip-demo) it's fixed right now 👍 👍
