### ISSUE TITLE
Problems with using TreeOfLife-10M Dataset

### ISSUE THREAD

**Issue by XavierHeart** [Imageomics/bioclip#22]
Hi, Congrats on your great work!!
I'm planning to use the Treeoflife dataset from the paper, but I'm having some problems downloading it for use. So far I've downloaded the dataset on [hf,](https://huggingface.co/datasets/imageomics/TreeOfLife-10M) as well as the inat21 dataset. But when I use the [script](https://github.com/Imageomics/bioclip/blob/main/docs/imageomics/treeoflife10m.md) file, I encounter some missing files. For example, when i tried to download most of the metadata files in [step1](https://github.com/Imageomics/bioclip/blob/main/scripts/download_data.sh), some urls are failed: wget https://eol.org/data/provider_ids.csv.gz.
Also, I'm trying to start from step 6 based on my previous issue, but I'm experiencing missing files at the same time: FileNotFoundError: [Errno 2] No such file or directory: '/fs/ess/PAS2136/eol/data/interim/media_cargo_archive'. 
Could you tell me how to use the dataset correctly? Or what data I'm missing to download. I'd appreciate more detailed guidance on this. 
Thanks and congrats again!!!

**Comment by egrace479** [comment]
Following the request in Issue #13, we've been working on a cleaner download process (PR #16, with improved instructions in PR #14). We're trying to ensure all the bugs are squashed before merging the update so [it's taking a bit longer than expected](https://github.com/Imageomics/bioclip/pull/16#issuecomment-2293399520). Please follow those PRs and Issue for updates. Also, we'd love to see what you do with the data!

**Comment by XavierHeart** [comment]
Thank you for your hard work and continuous updates! I plan to use this dataset for my academic research. I think it's cool to follow such work.
