### ISSUE TITLE
Missing examples?

### ISSUE THREAD

**Issue by afaulconbridge** [Imageomics/bioclip#26]
The readme says:

> See the examples/ directory for examples on how to use it. 

But there is no examples directory? is it somewhere else?

**Comment by egrace479** [comment]
Thank you for pointing that out. Yes, the examples directory is in the [Hugging Face model repo](https://huggingface.co/imageomics/bioclip).

**Comment by afaulconbridge** [comment]
Ah, great. Thanks for the quick reply and fix!
