### ISSUE TITLE
About iNat21 Dataset and Model Testing Procedures

### ISSUE THREAD

**Issue by XavierHeart** [Imageomics/bioclip#28]
I would like to express my appreciation for your outstanding work and contributions to the field~

I have a couple of questions that I hope you could assist me with:
    1. Would it be possible to share the scripts used for constructing the iNat21 dataset as mentioned in your paper? I am interested in understanding the construction process.
    2. Could you please elaborate on how the model was tested on the Plant and Animal test sets? My results seem to differ from those presented in the paper, and I would like to understand the potential reasons for this discrepancy.

Thank you very much for your time~~

**Comment by samuelstevens** [comment]
Hi, thanks for your interest. 

1. To construct iNat21, you can simply download the data from AWS. This page (https://github.com/visipedia/inat_comp/tree/master/2021) has links. For example, the train images are at https://ml-inat-competition-datasets.s3.amazonaws.com/2021/train.tar.gz. Then you can untar the file and extract the images.
2. To test on the Plant and Animal tasks, we perform k-shot nearest centroids classification, randomly selecting the k training examples each run to get a better estimation of true performance.

**Comment by egrace479** [comment]
All the dataset construction instructions are available in [docs/imageomics/treeoflife10m.md](https://github.com/Imageomics/bioclip/blob/main/docs/imageomics/treeoflife10m.md#how-to-create-treeoflife-10m). The first step will download all constituent pieces of TreeOfLife-10M (including iNat21). The bash scripts call the download scripts.

**Comment by XavierHeart** [comment]
> Hi, thanks for your interest.
> 
>     1. To construct iNat21, you can simply download the data from AWS. This page (https://github.com/visipedia/inat_comp/tree/master/2021) has links. For example, the train images are at https://ml-inat-competition-datasets.s3.amazonaws.com/2021/train.tar.gz. Then you can untar the file and extract the images.
> 
>     2. To test on the Plant and Animal tasks, we perform k-shot nearest centroids classification, randomly selecting the k training examples each run to get a better estimation of true performance.

Thanks!

**Comment by samuelstevens** [comment]
Closing, feel free to reopen if you still have questions.

**Comment by work4cs** [comment]
It is very common to have some discrepancy on performance due to the difference in GPU implementations such as optimization, pipeline, etc. But the exact same GPU clusters should give the same inference results.
