### ISSUE TITLE
About Unseen Categories

### ISSUE THREAD

**Issue by qiancunayllen** [Imageomics/bioclip#29]
Thank you for your significant contributions!

May I ask what datasets the unseen categories used for testing were derived from? Besides the Rare Species dataset, are there categories in iNat 21 or other datasets that were not seen during pre-training?

**Comment by samuelstevens** [comment]
No. We randomly sampled 400 species from the species listed on [The International Union for Conservation of Nature (IUCN) Red List](https://www.iucnredlist.org/) as Near Threatened, Vulnerable, Endangered, Critically Endangered, and Extinct in the Wild. 
We then grabbed 30 images of each species from EOL, and removed all other images of those species from TreeOfLife-10M. 
You might want to check the [dataset card](https://huggingface.co/datasets/imageomics/rare-species) for more information. 

I don't remember if any of these species overlap with any of the species in iNat21--you can check by simply comparing the list of species in RareSpecies and iNat21. 

Other than the 400 species in RareSpecies, there are no species explicitly removed from TreeOfLife-10M.

**Comment by qiancunayllen** [comment]
Thank you for your reply!
